name: Build and test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble

        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
